In [2]:
#importing the necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
#loading the dataset
credit_card = pd.read_csv('creditcard.csv')

In [4]:
credit_card.head()  #displaying the first 5 rows of the dataset

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [12]:
credit_card.info()  #dataset information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [11]:
credit_card.isnull().sum()  #checking for missing values

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [13]:
credit_card['Class'].value_counts()  #checking the number of legit and fraudulent transactions

Class
0    284315
1       492
Name: count, dtype: int64

In [14]:
#separating the legit and fraudulent transactions for analysis
legit = credit_card[credit_card.Class==0]
fraud = credit_card[credit_card.Class==1]

In [15]:
#checking their shapes
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [19]:
#statistics of the data
print(legit.Amount.describe())
print(fraud.Amount.describe())

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64
count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [20]:
#comparing mean values for both transactions
credit_card.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [21]:
#Balancing the data by building a simple dataset containing similar distribution of legit and fraudulent transactions

legit_sample = legit.sample(n=492)

In [22]:
#concatenating the two dataframes

new_credit = pd.concat([legit_sample, fraud], axis=0)

In [23]:
new_credit.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
147168,88204.0,-0.724686,1.705926,-1.147171,0.138444,1.465536,-1.267612,-0.202317,-2.967958,-0.720552,...,-1.013608,1.339976,-0.303022,-0.186559,-0.566831,-0.178887,0.283877,0.311134,1.00,0
26051,33888.0,1.313171,0.078188,-1.291722,-0.483959,2.140233,3.181208,-0.506359,0.805117,-0.073954,...,-0.343276,-1.147981,0.096151,0.946070,0.370076,0.110731,-0.021650,0.023466,0.99,0
93364,64376.0,1.115250,1.053562,-1.670961,1.707305,0.731498,-1.817506,0.839265,-0.381240,-0.392557,...,-0.173678,-0.574874,-0.263627,0.052837,0.818383,-0.300184,0.024352,0.107996,69.38,0
196513,131546.0,1.844129,-0.313811,0.170274,1.404138,-0.803035,-0.204432,-0.651906,0.030052,1.072305,...,0.089416,0.382561,0.242770,-0.037298,-0.345865,-0.758137,0.078761,-0.012269,45.00,0
27081,34379.0,-0.829073,-0.195397,2.746648,-0.578145,-0.862903,0.825399,-0.281476,0.502849,1.053326,...,0.038080,0.371591,-0.127416,0.110919,-0.100916,0.966651,0.051298,0.099679,65.55,0

In [24]:
new_credit['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [25]:
new_credit.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,102460.126016,0.028417,0.062562,-0.168556,-0.026379,0.001141,0.028465,0.086618,-0.091906,-0.046706,...,-0.013933,-0.004426,0.009289,-0.042708,0.048979,0.011831,0.011710,0.029489,0.022148,100.211768
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [26]:
#splitting the data into features

X = new_credit.drop(columns='Class', axis=1)
Y = new_credit['Class']

In [29]:
print(X)
print(Y)

            Time        V1        V2        V3        V4        V5        V6  \
147168   88204.0 -0.724686  1.705926 -1.147171  0.138444  1.465536 -1.267612
26051    33888.0  1.313171  0.078188 -1.291722 -0.483959  2.140233  3.181208
93364    64376.0  1.115250  1.053562 -1.670961  1.707305  0.731498 -1.817506
196513  131546.0  1.844129 -0.313811  0.170274  1.404138 -0.803035 -0.204432
27081    34379.0 -0.829073 -0.195397  2.746648 -0.578145 -0.862903  0.825399
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
147168 -0.202317 -2.967958 -0.720552  ...  0.607460 -1.013608  1.339976
26051  -0.506359  0.805117 -0.073954  ...  0.030718 -0.343276 -1.147981
93364   0.839265 -0.381240 -0.392557  ...  0.076246 -0.173678 -0.574874
196513 -0.651906  0.030052  1.072305  ... -0.132005  0.089416  0.382561
27081  -0.281476  0.502849  1.053326  ...  0.055691  0.038080  0.371591
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
147168 -0.303022 -0.186559 -0.566831 -0.178887  0.283877  0.311134    1.00
26051   0.096151  0.946070  0.370076  0.110731 -0.021650  0.023466    0.99
93364  -0.263627  0.052837  0.818383 -0.300184  0.024352  0.107996   69.38
196513  0.242770 -0.037298 -0.345865 -0.758137  0.078761 -0.012269   45.00
27081  -0.127416  0.110919 -0.100916  0.966651  0.051298  0.099679   65.55
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]
147168    0
26051     0
93364     0
196513    0
27081     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [30]:
#split dat into training and testing data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, stratify=Y, random_state=2)

In [31]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (688, 30) (296, 30)

In [33]:
#Training the Model with training data
model = LogisticRegression()
model.fit(X_train, Y_train)

C:\Users\jj\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [37]:
# Evaluating model based on accuracy score

X_train_pred = model.predict(X_train) 
training_data_accuracy = accuracy_score(X_train_pred, Y_train)  
print('Accuracy on training data: ', training_data_accuracy*100) # accuracy on training data

Accuracy on training data:  94.62209302325581

In [40]:
# accuracy on test data
X_test_pred = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_pred, Y_test)
print('Accuracy on test data: ', test_data_accuracy*100)

Accuracy on test data:  92.9054054054054